# Generated by Django 4.2 on 2023-04-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
