# Generated by Django 4.1.7 on 2023-04-13 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_tank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tank',
            name='fish',
        ),
    ]
